#170947487 setup react router dom
andela/devrepublic-bn-frontend pull request #6
Opened 2020-04-20 04:16 UTC by bbaime98

#### What does this PR do?
- setup react router dom
#### Description of Task to be completed?
- install react-router-dom dependency
- create components and views components
- create dummy paths and components
#### How should this be manually tested?
- clone repo
- run `npm run start:dev`
-access login page via `/login` path
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
- [#170947487](https://www.pivotaltracker.com/story/show/170947487)
#### Screenshots (if appropriate)
#### Questions:

2020-04-20 08:54 UTC, izzett222 requested changes

2020-04-20 08:54 UTC, izzett222 commented on src/components/authentication/login.js
> +export default Login;
@bbaime98 shouldn't the login page also be in the views folder?

2020-04-21 10:44 UTC, Ntare22 approved these changes

2020-04-21 10:46 UTC, izzett222 approved these changes

2020-04-21 11:27 UTC, Baraka-Mugisha approved these changes

2020-04-21 12:15 UTC, merged